[package]
name = "cryptocurrency_api_tests"
version = "0.1.0"
authors = ["Exonum Team <exonum@bitfury.com>"]

[dependencies]
iron = "0.5.1"
serde = "1.0.0"
serde_derive = "1.0.0"
rand = "0.3"
router = "0.5.1"
log = "0.3"
iron-test = { git = "https://github.com/reem/iron-test" }
cryptocurrency = {version="0.1.0", path="../cryptocurrency"}

[dependencies.exonum]
git = "https://github.com/exonum/exonum.git"
version = "0.1.0"
tag = "v0.1"

[dependencies.sandbox]
git = "https://github.com/exonum/exonum.git"
version = "0.1.0"
tag = "v0.1"

[replace]
"exonum:0.1.0" = { git = "https://github.com/exonum/exonum.git", tag="v0.1" }
