[package]
name = "cryptocurrency_api_tests"
version = "0.1.0"
authors = ["Oleg Kuzmin <oleg.kuzmin@bitfury.com>"]

[dependencies]
iron = "0.5.1"
serde = "1.0.0"
serde_derive = "1.0.0"
rand = "0.3"
router = "0.5.1"
log = "0.3"
iron-test = { git = "https://github.com/reem/iron-test" }
cryptocurrency = {version="0.1.0", path="../cryptocurrency"}

[dependencies.exonum]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "07840ee882865907e79147c0cd7870772fc9d5a5"

[dependencies.sandbox]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "07840ee882865907e79147c0cd7870772fc9d5a5"
