[package]
name = "sandbox"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re>"]

[dependencies]
exonum = {version="0.1", path="../exonum"}
timestamping = {version="0.1", path="../timestamping"}
env_logger = "0.3"
clap = {version="2.10.0", features=["unstable"]}
rand = "0.3"
time = "0.1"
serde = "0.7"
serde_macros = "0.7"
toml = {version="0.1.30", default-features=false, features=["serde"]}
