[package]
name = "sandbox"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re>"]

[dependencies]
exonum = {version="0.1", path="../exonum"}
env_logger = "0.3"
clap = {version="2.10.0", features=["unstable"]}
rand = "0.3"
timestamping = {version="0.1", path="../timestamping"}
time = "0.1"
