[package]
name = "exonum-derive"
version = "0.10.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/"
repository = "https://github.com/exonum/exonum"
documentation = "https://docs.rs/exonum-derive"
readme = "README.md"
license = "Apache-2.0"
keywords = ["protobuf", "exonum"]
categories = ["development-tools"]

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"
