language: rust

addons:
  apt:
    sources:
    - sourceline: 'ppa:giskou/librocksdb'
    packages:
    - gcc
    - g++
    - libssl-dev
    - librocksdb
    - libsnappy-dev

rust:
  - stable
matrix:
  allow_failures:
    - env: FEATURE=non-fatal-checks
  fast_finish: true
  include:
    - rust: nightly-2018-01-22
      env: FEATURE=clippy

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.local
  - $TRAVIS_BUILD_DIR/target

dist: trusty
sudo: required

env:
  global:
  - CLIPPY_VERS=0.0.181
  - RUSTFMT_VERS=0.9.0
  - DEADLINKS_VERS=0.3.0
  - SODIUM_VERS=1.0.13
  - CARGO_INCREMENTAL=1
  - ROCKSDB_LIB_DIR=/usr/lib/x86_64-linux-gnu
  - SNAPPY_LIB_DIR=/usr/lib/x86_64-linux-gnu
  matrix:
  - FEATURE=fmt
  - FEATURE=test
  - FEATURE=test-doc
  - FEATURE=non-fatal-checks

install:
- |
  if [ ! -f "$HOME/.local/lib/libsodium.a" ]; then
    wget "https://github.com/jedisct1/libsodium/releases/download/$SODIUM_VERS/libsodium-$SODIUM_VERS.tar.gz" -t 5 -O "libsodium.tar.gz"
    tar xvf libsodium.tar.gz
    cd libsodium-$SODIUM_VERS
    ./configure --prefix=$HOME/.local
    make
    make install
    cd ..
  fi
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig
- |
  if [[ "$FEATURE" == "non-fatal-checks" ]]; then
    cargo-deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
  fi
- |
  if [[ "$FEATURE" == "fmt" ]]; then
    cargo-audit -V || cargo install cargo-audit --force
    rustfmt -V | grep $RUSTFMT_VERS || cargo install rustfmt --vers $RUSTFMT_VERS --force
    cargo update
  fi
- |
  if [[ "$FEATURE" == "clippy" ]]; then
    cargo clippy --version | grep $CLIPPY_VERS || cargo install clippy --force --vers $CLIPPY_VERS
  fi
- cargo install --list

script: |
  case "$FEATURE" in

  "fmt" )
      cargo audit &&
      cargo fmt -- --write-mode=diff
  ;;
  "clippy" )
      cargo clippy -- -D warnings
  ;;
  "test" )
      cargo test --manifest-path Cargo.toml --verbose --tests --lib
  ;;
  "non-fatal-checks" )
      cargo doc --no-deps &&
      cargo deadlinks --dir target/doc
  ;;

  esac

notifications:
  slack:
    secure: qeciDAh7bWUwxuw6s2CrttvWJ8d4IAf5PojeDsUV+K1EacSA64sxkp/xAwvyxFVKof3CWrS3eCB0u3/4bHDgWMPKRa839gkXf+3I6SSDClkHxCffZ3zqS+u6E+riIknTFpsj7UvYVmtUZSIEKHyMuEou33KWkTTqQIX+sb5ExETygApKRuFzBMi8CwQLu7Djfg1Vv1FFqSqGDkxb+0C40bIJgHjUkVy225dJMS7s0zWpq1Z7QQ4mrVfeTD5rq2j7VJo0keqMUyFcY9MgSkHd8HOkvw4oBYJ5NV+BMOeRWA5kxDAAhinBfImj83lI8jfTIjTVrl3a5rK/rQ9Q2tJWuDHtbClMmHhTYo7/mc17Wbqozc0FhNZyXzml90Y9xvmgeP8pnSv8LntFr1+bYQmPnfleFk6Ub2khQ55zutDDxWxYW/aSuFaHZq92Fnk81UjM+51j8YzMhyQvIJcsCPnNc1XSFasyTiUOeztLeiGcKa5yHmwJQDSASpdn99EXkSEe4Cp074DxoTxRzblqIOswEiX+2kFv2oj9uwVmmcvTqqpKsFGSjBOsLy7Q+ld43zuVuZom4FtJKEv8971aJ6eKnK+a+Tms8SoYP1RC13P9S/DlIlPLg66QNzk4FCH7WQGxPjfzkxMH397zPdqMPsgTlTeqyqkIvfq4NFtBQ4cYnkw=
