[package]
name = "sandbox_tests"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>",
	   "Oleg Kuzmin <oleg.kuzmin@bitfury.com>"]

[dependencies]
configuration_service = {version="0.1.0", path="../"}
serde = "0.8.23"
serde_json = "0.8.6"
serde_derive = "0.8.0"
log = "0.3"
[dependencies.exonum]
git = "ssh://git@gitlab.xdev.re/digital-assets/digital-assets.git"
rev = "5a9e84bd8013bb2a772ffdd44eebd288ca8bad90"

[dependencies.blockchain_explorer]
git = "ssh://git@gitlab.xdev.re/digital-assets/digital-assets.git"
rev = "5a9e84bd8013bb2a772ffdd44eebd288ca8bad90"

[dependencies.sandbox]
git = "ssh://git@gitlab.xdev.re/digital-assets/digital-assets.git"
rev = "5a9e84bd8013bb2a772ffdd44eebd288ca8bad90"
