[package]
name = "sandbox_tests"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>",
	   "Oleg Kuzmin <oleg.kuzmin@xdev.re>"]

[dependencies]
iron = "0.5.1"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
rand = "0.3"
router = "0.5.1"
log = "0.3"
iron-test = { git = "https://github.com/reem/iron-test" }
configuration_service = {version="0.1.0", path="../"}

[dependencies.exonum]
git = "ssh://git@github.com/vldm/exonum-core.git"
version = "0.1.0"
rev = "2277c1406f74ef8e6a4cef2c7eb972a4af4909f3"

[dependencies.sandbox]
git = "ssh://git@github.com/vldm/exonum-core.git"
version = "0.1.0"
rev = "2277c1406f74ef8e6a4cef2c7eb972a4af4909f3"
