[package]
name = "sandbox_tests"
version = "0.1.0"
authors = ["Exonum Team <exonum@bitfury.com>"]

[dependencies]
iron = "0.5.1"
serde = "1.0.0"
serde_derive = "1.0.0"
rand = "0.3"
router = "0.5.1"
log = "0.3"
iron-test = { git = "https://github.com/reem/iron-test" }
configuration_service = {version="0.1.0", path="../"}

[dependencies.exonum]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "cf87780b3de1ba161c490e0700870a0f2c308136"

[dependencies.sandbox]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "cf87780b3de1ba161c490e0700870a0f2c308136"
