[package]
name = "sandbox_tests"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>",
           "Oleg Kuzmin <oleg.kuzmin@xdev.re>"]

[dependencies]
iron = "0.5.1"
serde = "1.0.0"
serde_derive = "1.0.0"
rand = "0.3"
router = "0.5.1"
log = "0.3"
iron-test = { git = "https://github.com/reem/iron-test" }
configuration_service = {version="0.1.0", path="../"}

[dependencies.exonum]
git = "ssh://git@github.com/gisochre/exonum-core.git"
version = "0.1.0"
rev = "1caa4862d28e1f1eca888a0c19cb544f5b62dc6c"

[dependencies.sandbox]
git = "ssh://git@github.com/gisochre/exonum-core.git"
version = "0.1.0"
rev = "1caa4862d28e1f1eca888a0c19cb544f5b62dc6c"
