[package]
name = "sandbox_tests"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>",
	   "Oleg Kuzmin <oleg.kuzmin@xdev.re>"]

[dependencies]
iron = "0.5.1"
serde = "0.8.23"
serde_derive = "0.8.0"
rand = "0.3"
serde_json = "0.8.6"
router = "0.5.1"
log = "0.3"
iron-test = { git = "https://github.com/reem/iron-test" }
configuration_service = {version="0.1.0", path="../"}

[dependencies.exonum]
git = "ssh://git@gitlab.xdev.re/digital-assets/digital-assets.git"
rev = "803f985a556ceeca8ed18256b83f90cfa0b2e370"

[dependencies.blockchain_explorer]
git = "ssh://git@gitlab.xdev.re/digital-assets/digital-assets.git"
rev = "803f985a556ceeca8ed18256b83f90cfa0b2e370"

[dependencies.sandbox]
git = "ssh://git@gitlab.xdev.re/digital-assets/digital-assets.git"
rev = "803f985a556ceeca8ed18256b83f90cfa0b2e370"
