language: rust

rust:
  - stable

cache: cargo
sudo: required
group: deprecated-2017Q2
dist: trusty

env:
  global:
    - NIGHTLY_RUST=nightly-2017-07-05
    - CLIPPY_VERS=0.0.142
    - RUSTFMT_VERS=0.9.0

before_install:
- rustfmt -V | grep $RUSTFMT_VERS || cargo install rustfmt --vers $RUSTFMT_VERS --force
- cargo-audit -V || cargo install cargo-audit --force
- rustup toolchain install $NIGHTLY_RUST
- cargo +$NIGHTLY_RUST clippy --version | grep $CLIPPY_VERS || cargo +$NIGHTLY_RUST install clippy --force --vers $CLIPPY_VERS
- sudo add-apt-repository -y ppa:chris-lea/libsodium
- sudo apt-get -qq update
- cargo install --list

install:
- sudo apt-get -qq --yes install gcc g++ make libsodium-dev libleveldb-dev libssl-dev

script:
- cargo fmt -p exonum-configuration -- --write-mode=diff
- cargo +$NIGHTLY_RUST clippy  -- -D warnings
- cd sandbox_tests
- cargo fmt -p exonum-configuration-sandbox -- --write-mode=diff
- cargo +$NIGHTLY_RUST clippy  -- -D warnings
- cd ..
- cargo test
- RUST_LOG=off cargo test --manifest-path sandbox_tests/Cargo.toml

notifications:
  slack:
    secure: FnDaD3+0m3+XqQmakHZF9zMvtXhRQczP8qoiAS471JFWpBQyXbp+v98K7dIyRAlqwiAFaJuTr8Zxsem8bzmBoUixML0AN2ekngI1S147LMITMov6PEuruxQHfaWjCJ2L8iZy6vUQH+afZcJmEVMhCVJijgFpHyngBcDrCxFg5QJXwWTXztWxQlcoyCz1U4E3EuJWm2w/8MZwRsD4L5RlwrfBpc7tVeETekhakR0iDYjn5mt0AD+lpBfHcppB3LE5JTIc7nQR4OmmWZ9JJbp6qbFcqn7WEUQsubJuAfSRVwosTZxjd0lPiK9gw8F7RaYvemV4A7Wmc7WNthDKkf7XZ79wMTrBvB2FnozZXvCnwTBrm/KadZtnv9F1Hof4a7F3p+F29RY+FV6AJGI4xtSZYRKFnUCUgmKxlZUYtQ9E8ToZsn/ZgsilVL3RWCnIF1PJW8nnQiT5b9QbyT9z1hDqifeloBW0WJDxCMGz/jKDNx9kiRdnytcXOFy/2koDbXtrIUchPmMdunpMGB0qk8LUgnmV1v7dWcBQlGWrg+OwdyUQqBdaLmKHAqQ9quK4EUxIolxoT+AN0prquuoRMY8uCVZ/LpaGMWKofoDoj9m12/uGxDJOAXZJ2dGhr/672mwvG+qX40JcF24aRAZaw5pQ4GLVUdtIuRy6TjgMEomqP64=
