language: rust

addons:
  apt:
    sources:
    - sourceline: 'ppa:giskou/librocksdb'
    packages:
    - gcc
    - g++
    - libssl-dev
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - libiberty-dev
    - libsnappy-dev
    - librocksdb

rust:
  - stable
matrix:
  fast_finish: true
  include:
    - rust: nightly-2017-11-22
      env: FEATURE=clippy
    - rust: nightly-2017-11-22
      env: FEATURE=clippy-sandbox

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.local
  - $TRAVIS_BUILD_DIR/target
  - $TRAVIS_BUILD_DIR/cryptocurrency_api_tests/target

dist: trusty
sudo: required

env:
  global:
  - CLIPPY_VERS=0.0.174
  - RUSTFMT_VERS=0.9.0
  - DEADLINKS_VERS=0.3.0
  - SODIUM_VERS=1.0.13
  - CARGO_INCREMENTAL=1
  - RUSTFLAGS="-C link-dead-code"
  - CODECOV_TOKEN=90006bf6-e4b7-4825-b880-8d19c4e21c21
  - ROCKSDB_LIB_DIR=/usr/lib/x86_64-linux-gnu
  - SNAPPY_LIB_DIR=/usr/lib/x86_64-linux-gnu
  matrix:
  - FEATURE=fmt
  - FEATURE=test
  - FEATURE=test-sandbox

install:
- |
  if [ ! -f "$HOME/.local/lib/libsodium.a" ]; then
    wget "https://github.com/jedisct1/libsodium/releases/download/$SODIUM_VERS/libsodium-$SODIUM_VERS.tar.gz" -t 5 -O "libsodium.tar.gz"
    tar xvf libsodium.tar.gz
    cd libsodium-$SODIUM_VERS
    ./configure --prefix=$HOME/.local
    make
    make install
    cd ..
  fi
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig
- |
  if [[ "$FEATURE" == "fmt" ]]; then
    cargo-audit -V || cargo install cargo-audit --force
    rustfmt -V | grep $RUSTFMT_VERS || cargo install rustfmt --vers $RUSTFMT_VERS --force
    cd backend && cargo update
    cd cryptocurrency_api_tests && cargo update && cd ..
    fi
- |
  case "$FEATURE" in
  clippy* )
    cargo clippy --version | grep $CLIPPY_VERS || cargo install clippy --force --vers $CLIPPY_VERS
  ;;
  esac
- cargo install --list
script: |
  case "$FEATURE" in
  "fmt" )
      cd backend && cargo audit && cargo fmt -- --write-mode=diff &&
      cd cryptocurrency_api_tests && cargo audit && cargo fmt -- --write-mode=diff
  ;;
  "clippy" )
      cd backend && cargo clippy --verbose -- -D warnings
  ;;
  "clippy-sandbox" )
      cd backend/cryptocurrency_api_tests && cargo clippy --verbose -- -D warnings
  ;;
  "test" )
      cd backend && cargo test --verbose
  ;;
  "test-sandbox" )
      cd backend/cryptocurrency_api_tests && cargo test --verbose
  ;;
  esac

notifications:
  slack:
    secure: OT5J1ZfUxziwZNBDU86Wgxttv+uE+bTuNOF8llwAP6LS4swvBVKAiEaq9rvLFQDs1B47CPijeAR75x/Hm7E8NZtV98SOVZtxv+9RySS5xFkLuIMqCymdw9QauP3T9e9D07aBPWqzTlMwI/auHQiuMveGY2IRyUnzCdj8ZktD+RyMsSy0nkVd6E8UUZD9BbAOFndKc9dFQyOgVRtkzoxliEDL8Rg+W8Tz0fLQp33pSkTLWq6cvCW6pS+KuBD5Vj4l+UsDru1JcPVZv93AgZJ7dctHzSfpxzMFLjNF5VofmhyWkUbEOPqstI7wT4dKNwZ8GmJn2Yy6uUA0EhgpGkvKWeX8BAdd8GpJISOPH/Th2ahShWAjniDsJGDjPqmHK53g6aAJAhFryonTI7VA7pvNG+k+cgui4ar1ZU3mjXUSVkPqxndiPXMgzCClhxZFmk62T9Jx+RdxXkhoje9ItScjYblZmGkyKYlDZHqa8AKlefEKCTqkkhf9+/eRrISvpi63+PgGTIHahHI2KViS9JATLwJ0e0dXpHASzq9bC3VhlI9AANoUue9QFIMQ06t65WwzuN6Kb1dOQrboR99S8VbZRoBvn0EE+DF/wS35448gyeGwg0My0ateeW7kQbpYgDHcRpVzan+k3i8JyZqXlJtRGKNKSoHYcYYLDzg1SaUQO8E=
