language: rust

addons:
  apt:
    sources:
    - sourceline: 'ppa:giskou/librocksdb'
    packages:
    - gcc
    - g++
    - libssl-dev
    - librocksdb
    - libsnappy-dev

rust:
  - stable
matrix:
  allow_failures:
    - env: FEATURE=non-fatal-checks
  fast_finish: true
  include:
    - rust: nightly-2017-11-05
      env: FEATURE=clippy

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.local
  - $TRAVIS_BUILD_DIR/target

dist: trusty
sudo: required

env:
  global:
  - CLIPPY_VERS=0.0.169
  - RUSTFMT_VERS=0.9.0
  - DEADLINKS_VERS=0.3.0
  - SODIUM_VERS=1.0.13
  - CARGO_INCREMENTAL=1
  - ROCKSDB_LIB_DIR=/usr/lib/x86_64-linux-gnu
  - SNAPPY_LIB_DIR=/usr/lib/x86_64-linux-gnu
  matrix:
  - FEATURE=fmt
  - FEATURE=test
  - FEATURE=test-doc
  - FEATURE=non-fatal-checks

install:
- |
  if [ ! -f "$HOME/.local/lib/libsodium.a" ]; then
    wget "https://github.com/jedisct1/libsodium/releases/download/$SODIUM_VERS/libsodium-$SODIUM_VERS.tar.gz" -t 5 -O "libsodium.tar.gz"
    tar xvf libsodium.tar.gz
    cd libsodium-$SODIUM_VERS
    ./configure --prefix=$HOME/.local
    make
    make install
    cd ..
  fi
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig
- |
  if [[ "$FEATURE" == "non-fatal-checks" ]]; then
    cargo-deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
    fi
- |
  if [[ "$FEATURE" == "fmt" ]]; then
    cargo-audit -V || cargo install cargo-audit --force
    rustfmt -V | grep $RUSTFMT_VERS || cargo install rustfmt --vers $RUSTFMT_VERS --force
    cd exonum && cargo update && cd ..
    fi
- |
  case "$FEATURE" in
  clippy* )
    cargo clippy --version | grep $CLIPPY_VERS || cargo install clippy --force --vers $CLIPPY_VERS
  ;;
  esac
- cargo install --list
script: |
  case "$FEATURE" in
  "fmt" )
      cargo &&
      cargo audit &&
      cargo fmt -- --write-mode=diff &&
  ;;
  "clippy" )
      cargo clippy --verbose --features long_benchmarks  -- -D warnings
  ;;
  "test" )
      cargo test --manifest-path exonum/Cargo.toml --verbose --tests --lib
  ;;
  "non-fatal-checks" )
      cargo doc --no-deps -p exonum &&
      cargo deadlinks --dir target/doc
  ;;
  "benchmarks" )
        RUST_LOG=off cargo bench --verbose --manifest-path exonum/Cargo.toml --features long_benchmarks --no-run
  ;;
  esac