os: Visual Studio 2015

environment:
  matrix:
  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc

# branches:
#   only:
#     - master

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - cmd: set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup update
  - rustc -vV
  - cargo -vV

## Build Script ##

cache:
   - './target'
   - '%USERPROFILE%\.cargo'

build_script:
  - cargo build --release %cargoflags%

test_script:
  - cargo test --release %cargoflags%
