[package]
name = "configuration_service"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>",
           "Oleg Kuzmin <oleg.kuzmin@xdev.re>"]

[dependencies]
clap = "2.14"
tempdir = "0.3.5"
env_logger = "0.3"
log = "0.3"
serde = "1.0.0"
serde_derive = "1.0.0"
lazy_static = "0.2.1"

router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.7.0"
params = "0.6.0"

[dependencies.exonum]
git = "ssh://git@github.com/vldm/exonum-core.git"
version = "0.1.0"
rev = "6eb0ee84af14af7d85c2ad70d426b721bfb6ed3f"
