[package]
name = "da"
version = "0.1.0"
authors = ["Bitfury Inc. <ivan.ivashchenko@xdev.re>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
rand = "0.3"
mio = "0.5"
time = "0.1"
byteorder = "0.5"
sodiumoxide = {version="0.0.10", default-features=false}
leveldb = "0.8.3"
db-key = "0.0.5"
tempdir = "0.3.4"