[package]
name = "configuration_service"
version = "0.1.0"
authors = ["Exonum Team <exonum@bitfury.com>"]

[dependencies]
clap = "2.14"
tempdir = "0.3.5"
env_logger = "0.3"
log = "0.3"
serde = "1.0.0"
serde_derive = "1.0.0"
lazy_static = "0.2.1"

router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.7.0"
params = "0.6.0"

[dependencies.exonum]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "cf87780b3de1ba161c490e0700870a0f2c308136"

