[workspace]
members = [
    "exonum",
    "testkit",
    "services/configuration",
    "services/time",
    "examples/cryptocurrency",
    "examples/cryptocurrency-advanced",
]
exclude = [ "3rdparty", "exonum/fuzz" ]
