[package]
name = "cryptocurrency"
version = "0.1.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]

[dependencies]
iron = "0.5.1"
bodyparser = "0.7.0"
router = "0.5.1" 
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.exonum]
git = "ssh://git@github.com/exonum/exonum.git"
rev = "912fdff86e8294b822069f0e711167ca0a7adf1c"
