[package]
name = "exonum-time"
version = "0.1.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://github.com/exonum/exonum-time"
repository = "https://github.com/exonum/exonum-time"
documentation = "https://docs.rs/exonum-time"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "time"]
categories = ["cryptography", "date-and-time"]
description = "The time oracle service for Exonum."

[dependencies]
exonum = "0.3.0"
iron = "0.5.1"
bodyparser = "0.7.0"
router = "0.5.1"
serde = "1.0.10"
serde_json = "1.0.2"
serde_derive = "1.0.10"

[dev-dependencies.exonum-testkit]
git = "https://github.com/alekseysidorov/exonum-testkit"
rev = "6b22c464efceaa5deb15ecb2eb40a3fca24e97f4"

[patch.crates-io]
exonum = { git = "https://github.com/exonum/exonum", rev = "adb1a9ab47a356b6efb3ef73755f981f6fd0af9a" }
