[package]
name = "exonum-testkit"
version = "0.1.0"
license = "Apache-2.0"
homepage = "https://exonum.com"
description = """
Testkit for Exonum blockchain framework, allowing to test service APIs
synchronously.
"""
categories = ["test"]

[dependencies]
exonum = "0.3.0"
futures = "0.1.14"
serde = "1.0.0"
serde_json = "1.0.0"
mount = "0.3.0"
iron = "0.5.1"
iron-test = "0.5.0"
router = "0.5.1"

[dev-dependencies]
bodyparser = "0.7.0"
serde_derive = "1.0.0"

[patch.crates-io]
exonum = { git = "https://github.com/exonum/exonum", rev = "adb1a9ab47a356b6efb3ef73755f981f6fd0af9a" }
