[package]
name = "configuration_service"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>",
	   "Oleg Kuzmin <oleg.kuzmin@xdev.re>"]

[dependencies]
clap = "2.14"
env_logger = "0.3"
log = "0.3"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
lazy_static = "0.2.1"

router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.5.0"
params = "0.6.0"
clippy = {version = "0.0.107", optional = true}

[dependencies.exonum]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "6804712b34210a9643132d12c34c34cc18eb0384"

[dependencies.blockchain_explorer]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "6804712b34210a9643132d12c34c34cc18eb0384"
