[package]
name = "exonum-time"
version = "0.1.0"
authors = ["Serhii Oryshych <serhii.oryshych@xdev.re>"]

[dependencies]
exonum = "0.3.0"
iron = "0.5.1"
bodyparser = "0.7.0"
router = "0.5.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"