[package]
name = "minibank"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]

[dependencies]
exonum = { git = "ssh://git@github.com/exonum/exonum-core.git", features = [ "memorydb" ] }
