[package]
name = "configuration_service"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>",
	   "Oleg Kuzmin <oleg.kuzmin@bitfury.com>"]

[dependencies]
clap = "2.14"
env_logger = "0.3"
log = "0.3"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
lazy_static = "0.2.1"

router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.5.0"
params = "0.6.0"
#exonum = {version="0.1", path="../../dig2/digital-assets/exonum"} 
#blockchain_explorer = {version="0.1", path="../../dig2/digital-assets/blockchain_explorer"}

[dependencies.exonum]
git = "ssh://git@gitlab.xdev.re/digital-assets/digital-assets.git"
rev = "5a9e84bd8013bb2a772ffdd44eebd288ca8bad90"

[dependencies.blockchain_explorer]
git = "ssh://git@gitlab.xdev.re/digital-assets/digital-assets.git"
rev = "5a9e84bd8013bb2a772ffdd44eebd288ca8bad90"
