[package]
name = "minibank"
version = "0.1.0"
authors = ["Exonum Team <exonum@bitfury.com>"]

[dependencies]
iron = "0.5.1"
bodyparser = "0.7.0"
router = "0.5.1" 
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.exonum]
git = "ssh://git@github.com/exonum/exonum-core.git"
rev = "cf87780b3de1ba161c490e0700870a0f2c308136"
