[package]
name = "da"
version = "0.1.0"
authors = ["Bitfury Inc. <ivan.ivashchenko@xdev.re>"]
build = "build.rs"

[dependencies]
log = "0.3"
env_logger = "0.3"
mio = "0.5"
protobuf = "1.0"
capnp = "0.7"
sodiumoxide = {version="0.0.10", default-features=false}

[build-dependencies]
capnpc = "0.7"
