[package]
name = "timestamping"
version = "0.1.0"
authors = ["Aleksei Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
clap = "2.22"
env_logger = "0.4"

params = "0.8"
router = "0.6"
iron = "0.6"
bodyparser = "0.8"

rand = "0.3"
log = "0.3"
byteorder = "1.0"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

exonum = "0.4.0"
exonum-configuration = "0.4"
exonum-btc-anchoring = { version = "0.4.0", optional = true }

[dev-dependencies]
iron-test = "0.6"
exonum-testkit = "0.1"
mime = "0.2"

[dev-dependencies.sandbox]
git = "https://github.com/exonum/exonum.git"
version = "0.4.0"
tag = "v0.4"

[replace."exonum:0.4.0"]
git = "https://github.com/exonum/exonum.git"
tag = "v0.4"

[features]
default = []
anchoring = ["exonum-btc-anchoring"]
