[package]
name = "cryptocurrency"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re"]

[dependencies]
env_logger = "0.3"
clap = {version="2.14", features=["unstable"]}

time = "0.1"
rand = "0.3"
log = "0.3"
byteorder = "0.5"
serde = "0.8.23"
serde_derive = "0.8"
jsonway = "1.0"
iron = "0.5.1"
bodyparser = "0.5.0"
router = "0.5.1"
headers = "0.1.0"
hyper = "0.10.4"
serde_json = "0.8"
cookie = "0.6.0"
tempdir = "0.3.5"
params = "0.6.0"

[dependencies.exonum]
git = "ssh://git@github.com/alekseysidorov/exonum-core.git"
version = "0.1.0"
rev = "4f66b05e7b634254073dee509b3eff7d741f1857"

[dependencies.configuration_service]
git = "ssh://git@github.com/alekseysidorov/exonum-configuration.git"
version = "0.1.0"
rev = "cb9e6ac56952fae51213bd9efab42f617ee4601d"
