[package]
name = "timestamping"
version = "0.1.0"
authors = ["Aleksei Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
clap = "2.22.0"
env_logger = "0.4.0"
derive-error = "0.0.3"

params = "0.6.0"
router = "0.5.1"
iron = "0.5.1"

chrono = "0.3.0"
rand = "0.3.0"
log = "0.3.0"
byteorder = "1.0.0"
bitcoin = "0.9.1"

serde = "0.8.0"
serde_derive = "0.8.0"
serde_json = "0.8.0"
colored = "1.3.0"

[dependencies.exonum]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "5bd7cdea015e011b635a8ce89945f45b5f3f3805"

[dependencies.blockchain_explorer]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "5bd7cdea015e011b635a8ce89945f45b5f3f3805"

[dependencies.anchoring_btc_service]
git = "ssh://git@github.com/exonum/exonum-btc-anchoring.git"
version = "0.1.0"
rev = "c9d832158b8b0f76cf713eea64a050fc6abd85f4"

[dependencies.configuration_service]
git = "ssh://git@github.com/exonum/exonum-configuration.git"
version = "0.1.0"
rev = "95cd87fde82f09506261eb006955b55d1989f288"