[package]
name = "timestamping"
version = "0.1.0"
authors = ["Aleksei Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
clap = "2.14"
env_logger = "0.3"

params = "0.5"
iron = "0.4"
hyper = "0.9"
router = "0.4.0"

time = "0.1"
rand = "0.3"
log = "0.3"
byteorder = "0.5"

serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
colored = "1.3"

[dependencies.exonum]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"

[dependencies.blockchain_explorer]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"

