[package]
name = "timestamping"
version = "0.1.0"
authors = ["Aleksei Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
clap = "2.22.0"
env_logger = "0.4.0"

params = "0.6.0"
router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.7.0"

rand = "0.3.0"
log = "0.3.0"
byteorder = "1.0.0"

serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"

exonum = "0.2.0"
exonum-configuration = "0.2.0"
exonum-btc-anchoring = { version = "0.2.0", optional = true }

[dev-dependencies]
iron-test = "0.5.0"
mime = "0.2.0"

[dev-dependencies.sandbox]
git = "https://github.com/exonum/exonum.git"
version = "0.2.0"
tag = "v0.2"

[replace."exonum:0.2.0"]
git = "https://github.com/exonum/exonum.git"
tag = "v0.2"

[features]
default = []
anchoring = ["exonum-btc-anchoring"]
