[package]
name = "timestamping"
version = "0.1.0"
authors = ["Aleksei Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
clap = "2.22.0"
env_logger = "0.4.0"

params = "0.6.0"
router = "0.5.1"
iron = "0.5.1"

chrono = "0.3.0"
rand = "0.3.0"
log = "0.3.0"
byteorder = "1.0.0"
bitcoin = "0.9.1"

serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"

[dependencies.exonum]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "3a4c74df9f9fe0787b60612018190fa0f0a6f7ad"

[dependencies.anchoring_btc_service]
git = "ssh://git@github.com/exonum/exonum-btc-anchoring.git"
version = "0.1.0"
rev = "2b3b0a8d6a2b77cee1d0d674b82dcb305816f5ff"

[dependencies.configuration_service]
git = "ssh://git@github.com/exonum/exonum-configuration.git"
version = "0.1.0"
rev = "daf0e0a6dfb3067fbc6ad7e2078b56c89745c550"