[package]
name = "exonum"
version = "0.1.0"
authors = ["Bitfury Inc. <ivan.ivashchenko@xdev.re>"]

[dependencies]
log = "0.3"
mio = "0.5"
time = "0.1"
byteorder = "0.5"
leveldb = "0.8"
db-key = "0.0.5"
num = "0.1"
sodiumoxide = {version="0.0.12", default-features=false}
rand = "0.3"

[dev-dependencies]
tempdir = "0.3.4"
clap = {version="2.10.0", features=["unstable"]}
clippy = "0.0.80"
