[package]
name = "exonum"
version = "0.1.0"
authors = ["Bitfury Inc. <ivan.ivashchenko@xdev.re>"]

[dependencies]
log = "0.3"
mio = "0.5"
time = "0.1"
byteorder = "0.5"
db-key = "0.0.5"
num = "0.1"
sodiumoxide = {version="0.0.12"}
rand = "0.3"
clippy = {version="0.0.81", optional=true}
leveldb = {git = "ssh://git@gitlab.xdev.re/aleksei.sidorov/leveldb.git"}

[dev-dependencies]
tempdir = "0.3.4"
env_logger = "0.3"

[features]
default = []

long_benchmarks = []
